# Generated by Django 3.0.2 on 2020-01-04 02:55

import GhostPost.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete',
            field=models.CharField(default=GhostPost.models.deleteId, editable=False, max_length=6),
        ),
    ]
